networks:
  net:
    external: false
    name: ${NETWORK}

volumes:
  letsencrypt:
  htpasswd:
  wg-easy:


services:
  wg-easy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.WireGuardService.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.WireGuardRoute.service=WireGuardService"
      - "traefik.http.routers.WireGuardRoute.rule=Host(`${WG_HOST}`)"
      - "traefik.http.routers.WireGuardRoute.entrypoints=http"
      - "traefik.http.routers.WireGuardRoute.middlewares=panel-auth"
      - "traefik.http.routers.WireGuardRouteSSL.service=WireGuardService"
      - "traefik.http.routers.WireGuardRouteSSL.rule=Host(`${WG_HOST}`)"
      - "traefik.http.routers.WireGuardRouteSSL.middlewares=panel-auth"
      - "traefik.http.routers.WireGuardRouteSSL.entrypoints=https"
      - "traefik.http.routers.WireGuardRouteSSL.tls.certresolver=letsencrypt"
    env_file:
      - .env
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    networks:
      - net
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
    expose:
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  traefik:
    image: traefik:latest
    container_name: traefik
    env_file:
      - .env
    command:
      - "--providers.docker"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${NETWORK}"
      - "--log.level=${LOG_LEVEL}"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.panel-auth.basicauth.usersfile=/htpasswd/users"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./htpasswd:/htpasswd
    networks:
      - net
    ports:
      - "80:80"
      - "${HTTPS_PANEL_PORT}:443"
