providers:
  docker:
    watch: true
    exposedbydefault: false
    network: ${NETWORK}

entrypoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesresolvers:
  letsencrypt:
    acme:
      email: ${LE_EMAIL}
      storage: /letsencrypt/acme.json
      tlschallenge: true
      httpChallenge:
        entryPoint: http

api:
  dashboard: false
  insecure: true
  debug: true
  
log:
  level: ${LOG_LEVEL}